# Generated by Django 2.1.11 on 2019-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phone_verify", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="smsverification",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="OTP is Verified"),
        )
    ]
