# Generated by Django 3.1.0 on 2025-01-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_verify', '0002_auto_20190817_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Attempts'),
        ),
    ]
